ARG LANGUAGE_VERSION=22.13.0
FROM node:${LANGUAGE_VERSION}-alpine
COPY repo /bot
WORKDIR /bot

ARG MAIN_FILE
ENV MAIN_FILE=${MAIN_FILE}

ARG PACKAGE_MANAGER=npm
RUN ${PACKAGE_MANAGER} install
CMD node ${MAIN_FILE}