[tail]
name = "javascript-node"
display_name = "JavaScript (Legacy Node.js)"
description = "The classic Node.js runtime, with your choice of npm, pnpm, or yarn."
last_modified = 2025-01-17

[config.main_file]
type = "string"
default = "index.js"
arg = "MAIN_FILE"
description = "The main file to run when starting your bot."

[config.language_version]
type = "string"
default = "22.13.0"
arg = "LANGUAGE_VERSION"
description = "Version of Node.js to use."

[config.package_manager]
type = "string"
default = "npm"
arg = "PACKAGE_MANAGER"
description = "Package manager to use."
options = ["npm", "pnpm", "yarn"]