[tail]
name = "rust"
display_name = "Rust"
description = "A native binary approach to Discord bots with Rust"
last_modified = 2025-10-26

[config.binary_name]
type = "string"
default = "bot"
arg = "BINARY_NAME"
description = "Name of the binary package to build"

[config.language_version]
type = "string"
default = "1.84.0"
arg = "LANGUAGE_VERSION"
description = "Rust version to use."
